# Material y Metodos
## Origen de los datos:
1. GBIF
2. WorldClim 
3. Lista de especies invasoras
4. Open Tree of Life


## Workflow
1) Descarga de datos de registros de presencia de especies de la familia de las Aizoaceas de GBIF
2) Descarga de datos de las variables bioclimaticas del WordClim para las coordenadas de presencia de especies de (1).
3) Descarga de los datos filogeneticos de las especies de Aizoaceas del Open Tree of Life
4) Construccion del nicho climatico de las especies de la familia de las Aizoaceas con PCA (individual y comun)
5) Parametrizacion del nicho climatico (que variables podemos extraer?: anchura del nicho por ejemplo)
6) Construccion de un entorno shinny para la visualización del nicho climatico de las especies categorizando su origen y si son o no invasoras.
7) Relacionar la filogenia con los parametros del nicho ecologico
8) Encontrar especies similares en cuanto a su nicho climatico. Hay especies muy parecidas a Carpobrotus edulis?

## Descripción del procedimiento seguido
Descripción de los paquetes usados, assumciones tomadas, etc..
