---
title: "R Notebook"
output: html_notebook
---

## Assesoramiento del riesgo invasor en la Península Iberica.

# INDICE DE CONTENIDOS
# 1. PREGUNTAS Y DEFINICIONES INICIALES
# 2. PAQUETES NECESARIOS
# 3. DELIMITACIÓN DEL MARCO CLIMÁTICO IBÉRICO
# 4. DESCARTAR VARIABLES MUY CORRELACIONADAS
# 5. REDUCCIÓN DE DIMENSIONES POR PCA
# 6. OBTENCIÓN DE DATOS DE OTROS PAISES Y PROYECCIÓN SOBRE EL MARCO CLIMÁTICO IBÉRICO 



# 1. PREGUNTAS Y DEFINICIONES INICIALES
# 1.1 Preguntas
Si las invasiones son exitosas por en coincidencia del clima, ¿que especies estarian bien en la peninsula iberica y son por tanto potenciales invasores?

¿Las especies invasoras actuales en la peninsula iberica cumplen esa hipotesis de coincidencia del clima?
Si las condiciones climaticas en la peninsula cambiasen en el contexto del cambio climatico, ¿el numero de especies potencialmente invasoras seria mayor, menor o igual? ¿El cambio climatico podria potenciar la amenaza invasora?

Teniendo en cuenta el origen de las especies potencialmente invasoras y los movimientos globales de mercancias y personas, ¿Que invasiones son mas probables? ¿Con que paises deberiamos endurecer las politicas de comercio de especies?

¿Por que superficie se extenderian las especies potencialmente invasoras en la peninsula? ¿Cuanto es su daño potencial?

Teniendo en cuenta las condiciones climáticas en la península, ¿que otros países de Europa pueden ser susceptibles a la invasión debido a similaridades con el marco climático de España i Portugal?

# 1.2. Definiciones
Marco climatico Ibérico: espacio multidimensional definido por los valores de diferentes variables bioclimáticas georeferenciados dentro de la Peninsula Ibérica.

Variable bioclimática: Variable descriptora ambiental considerada determinante para el crecimiento, desarrollo y reproducción de la biosfera.

Nicho climático: espacio multidimensional definido por los valores de diferentes variables bioclimáticas de los puntos de presencia de una especie.

Especie potencialmente invasora en la Peninsula Iberica: especie cuyo nicho climático está comprendido dentro del Marco climático Ibérico.

# 2. PAQUETES NECESARIOS
```{r}
install.packages("raster")
library("raster")
library(sp)
install.packages("dismo")
library("dismo")
library(readr)
library(ggplot2)
install.packages("plotly")
library(plotly)
library(MASS)
require(MASS)
install.packages("fmsb")
library(fmsb)
library(devtools)
install_github("ggbiplot", "vqv")
library(ggbiplot)
install.packages("factoextra")
library(factoextra)

# setwd("C:/Users/Desktop/DataSciencePlantsESTESI") 

```